name: GlassCalc
options:
  bundleIdPrefix: com.laclairtech
  deploymentTarget:
    iOS: 18.0

schemes:
  GlassCalc:
    build:
      targets:
        GlassCalc: all
        GlassCalcWidgetExtension: all
    run:
      config: Debug
      storeKitConfiguration: App/Configuration.storekit
    test:
      config: Debug
      targets:
        - GlassCalcTests

targets:
  GlassCalc:
    type: application
    platform: iOS
    sources:
      - App
      - path: Sources/GlassCalc
        excludes:
          - Widgets/**
    dependencies:
      - target: GlassCalcWidgetExtension
    entitlements:
      path: App/GlassCalc.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.laclairtech.glasscalc
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      SWIFT_VERSION: 6.0
      TARGETED_DEVICE_FAMILY: 1,2
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      CODE_SIGN_ENTITLEMENTS: App/GlassCalc.entitlements
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES

  GlassCalcWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - WidgetExtension
      - Sources/GlassCalc/Widgets
      - path: Sources/GlassCalc/Core/Services/SharedDataService.swift
        group: Services
      - path: Sources/GlassCalc/Core/Intents/GlassCalcIntents.swift
        group: Intents
    dependencies:
      - framework: SwiftUI.framework
        implicit: true
      - framework: WidgetKit.framework
        implicit: true
    entitlements:
      path: WidgetExtension/GlassCalcWidget.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.laclairtech.glasscalc.widget
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: 6.0
      TARGETED_DEVICE_FAMILY: 1,2
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      INFOPLIST_KEY_CFBundleDisplayName: GlassCalc Widget
      CODE_SIGN_ENTITLEMENTS: WidgetExtension/GlassCalcWidget.entitlements
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
    info:
      path: WidgetExtension/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

  GlassCalcTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/GlassCalcTests
    dependencies:
      - target: GlassCalc
    settings:
      SWIFT_VERSION: 6.0
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.laclairtech.glasscalc.tests
