name: PrismCalc
options:
  bundleIdPrefix: com.laclairtech
  deploymentTarget:
    iOS: 18.0

schemes:
  PrismCalc:
    build:
      targets:
        PrismCalc: all
        PrismCalcWidgetExtension: all
    run:
      config: Debug
      storeKitConfiguration: App/Configuration.storekit
    test:
      config: Debug
      targets:
        - PrismCalcTests

targets:
  PrismCalc:
    type: application
    platform: iOS
    sources:
      - App
      - App/PrivacyInfo.xcprivacy
      - path: Sources/PrismCalc
        excludes:
          - Widgets/**
    dependencies:
      - target: PrismCalcWidgetExtension
    entitlements:
      path: App/PrismCalc.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.laclairtech.prismcalc
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      SWIFT_VERSION: 6.0
      TARGETED_DEVICE_FAMILY: 1,2
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      CODE_SIGN_ENTITLEMENTS: App/PrismCalc.entitlements
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
      INFOPLIST_KEY_CFBundleDisplayName: PrismCalc

  PrismCalcWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - WidgetExtension
      - Sources/PrismCalc/Widgets
      - path: Sources/PrismCalc/Core/Services/SharedDataService.swift
        group: Services
      - path: Sources/PrismCalc/Core/Intents/PrismCalcIntents.swift
        group: Intents
    dependencies:
      - framework: SwiftUI.framework
        implicit: true
      - framework: WidgetKit.framework
        implicit: true
    entitlements:
      path: WidgetExtension/PrismCalcWidget.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.laclairtech.prismcalc.widget
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: 6.0
      TARGETED_DEVICE_FAMILY: 1,2
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      INFOPLIST_KEY_CFBundleDisplayName: PrismCalc Widget
      CODE_SIGN_ENTITLEMENTS: WidgetExtension/PrismCalcWidget.entitlements
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
    info:
      path: WidgetExtension/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

  PrismCalcTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/PrismCalcTests
    dependencies:
      - target: PrismCalc
    settings:
      SWIFT_VERSION: 6.0
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.laclairtech.prismcalc.tests
