name: GlassCalc
options:
  bundleIdPrefix: com.laclairtech
  deploymentTarget:
    iOS: 18.0

targets:
  GlassCalc:
    type: application
    platform: iOS
    sources: [App, Sources/GlassCalc]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.laclairtech.glasscalc
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      SWIFT_VERSION: 6.0
      TARGETED_DEVICE_FAMILY: 1,2
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
